Sender: LSF System <lsfadmin@node194.hpc.local>
Subject: Job 91986697: <bash run_eqtl_chr2.sh "Excitatory Neuron"> in cluster <pennhpc> Exited

Job <bash run_eqtl_chr2.sh "Excitatory Neuron"> was submitted from host <hpclogin1> by user <hamdan1> in cluster <pennhpc> at Tue May 27 09:25:05 2025
Job was executed on host(s) <node194.hpc.local>, in queue <normal>, as user <hamdan1> in cluster <pennhpc> at Tue May 27 09:25:06 2025
</home/hamdan1> was used as the home directory.
</project/guomiclab/hamdanz_projects/adsp_r4_rosmap> was used as the working directory.
Started at Tue May 27 09:25:06 2025
Terminated at Tue May 27 13:48:30 2025
Results reported at Tue May 27 13:48:30 2025

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
bash run_eqtl_chr2.sh "Excitatory Neuron"
------------------------------------------------------------

TERM_MEMLIMIT: job killed after reaching LSF memory usage limit.
Exited with exit code 130.

Resource usage summary:

    CPU time :                                   15683.00 sec.
    Max Memory :                                 180000 MB
    Average Memory :                             110927.61 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   2 MB
    Max Processes :                              40
    Max Threads :                                51
    Run time :                                   15804 sec.
    Turnaround time :                            15805 sec.

The output (if any) follows:

/project/guomiclab/hamdanz_projects/adsp_r4_rosmap/src/helper_functions.py:72: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  gtf = pd.read_csv(GTF_PATH, sep='\t', header= None, comment = '#')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
/project/guomiclab/hamdanz_projects/adsp_r4_rosmap/data/adsp_r4_rosmap/chr2.rosmap.r4.wgs.biallelic.genotypes.mac10.corrected.txt.gz exists! continuing...
data/rnaseq/rosmap_raw_rnaseq_labeled.h5ad exists! continuing...
data/metadata/ROSMAP_covariates.csv exists! continuing...
Importing Packages...
Packages finished importing
Found 770 matching SNP IDs in the SNP dataframe
READING IN RNA-SEQ DATA...
FINISHED READING RNA-SEQ DATA
Column name subject_key found in dataframe. Continuing...
Column name major_cell_type found in dataframe. Continuing...
Found Excitatory Neuron in the adata object
BUILDING GTF REFERENCE DATAFRAME...
FINISHED BUILDING GTF REFERENCE DATAFRAME
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  1.9min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  1.9min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  1.9min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  1.9min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.5min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.3min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.4min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.2min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.1min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.1min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.5min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  1.9min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  1.9min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.2min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.4min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.3min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.0min finished
Traceback (most recent call last):
  File "/project/guomiclab/hamdanz_projects/adsp_r4_rosmap/src/run_eqtl.py", line 177, in <module>
    eqtl_results = memento.run_eqtl(adata=adata,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/wrappers.py", line 34, in run_eqtl
    memento.setup_memento(adata, q_column ='capture_rate', trim_percent=0.1, filter_mean_thresh=mean_expr_threshold, estimator_type='mean_only')
  File "/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py", line 81, in setup_memento
    all_m[adata.X.mean(axis=0).A1 < filter_mean_thresh] = 0 # mean filter
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/scipy/sparse/_base.py", line 1191, in mean
    return (inter_self * (1.0 / self.shape[0])).sum(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/scipy/sparse/_compressed.py", line 646, in sum
    return _spbase.sum(self, axis=axis, dtype=dtype, out=out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/scipy/sparse/_base.py", line 1108, in sum
    ret = self._ascontainer(
          ^^^^^^^^^^^^^^^^^^
  File "/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/scipy/sparse/_base.py", line 675, in __rmatmul__
    return self._rmatmul_dispatch(other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/scipy/sparse/_base.py", line 656, in _rmatmul_dispatch
    ret = self.transpose()._matmul_dispatch(tr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/scipy/sparse/_base.py", line 600, in _matmul_dispatch
    result = self._matmul_vector(np.ravel(other))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/scipy/sparse/_compressed.py", line 492, in _matmul_vector
    fn(M, N, self.indptr, self.indices, self.data, other, result)
KeyboardInterrupt
Sender: LSF System <lsfadmin@node154.hpc.local>
Subject: Job 91991607: <bash run_eqtl_chr2.sh "Excitatory Neuron"> in cluster <pennhpc> Exited

Job <bash run_eqtl_chr2.sh "Excitatory Neuron"> was submitted from host <hpclogin1> by user <hamdan1> in cluster <pennhpc> at Wed May 28 08:49:54 2025
Job was executed on host(s) <node154.hpc.local>, in queue <normal>, as user <hamdan1> in cluster <pennhpc> at Wed May 28 08:49:55 2025
</home/hamdan1> was used as the home directory.
</project/guomiclab/hamdanz_projects/adsp_r4_rosmap> was used as the working directory.
Started at Wed May 28 08:49:55 2025
Terminated at Wed May 28 19:21:04 2025
Results reported at Wed May 28 19:21:04 2025

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
bash run_eqtl_chr2.sh "Excitatory Neuron"
------------------------------------------------------------

TERM_MEMLIMIT: job killed after reaching LSF memory usage limit.
Exited with exit code 137.

Resource usage summary:

    CPU time :                                   36937.00 sec.
    Max Memory :                                 180000 MB
    Average Memory :                             115474.76 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   2 MB
    Max Processes :                              41
    Max Threads :                                53
    Run time :                                   37869 sec.
    Turnaround time :                            37870 sec.

The output (if any) follows:

/project/guomiclab/hamdanz_projects/adsp_r4_rosmap/src/helper_functions.py:72: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  gtf = pd.read_csv(GTF_PATH, sep='\t', header= None, comment = '#')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
/project/guomiclab/hamdanz_projects/adsp_r4_rosmap/data/adsp_r4_rosmap/chr2.rosmap.r4.wgs.biallelic.genotypes.mac10.corrected.txt.gz exists! continuing...
data/rnaseq/rosmap_raw_rnaseq_labeled.h5ad exists! continuing...
data/metadata/ROSMAP_covariates.csv exists! continuing...
Importing Packages...
Packages finished importing
Found 770 matching SNP IDs in the SNP dataframe
READING IN RNA-SEQ DATA...
FINISHED READING RNA-SEQ DATA
Column name subject_key found in dataframe. Continuing...
Column name major_cell_type found in dataframe. Continuing...
Found Excitatory Neuron in the adata object
BUILDING GTF REFERENCE DATAFRAME...
FINISHED BUILDING GTF REFERENCE DATAFRAME
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  3.3min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.5min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  3.4min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  3.1min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.9min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.3min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.3min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  5.3min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  5.4min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.7min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.8min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.7min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.8min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.7min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.3min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.3min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.5min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.4min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.7min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.8min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  3.0min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.5min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.5min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.5min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.7min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/estimator.py:94: RankWarning: Polyfit may be poorly conditioned
  poly = np.polyfit(m, v, 2)
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
blocksize 10
working on block 0
8
[Parallel(n_jobs=32)]: Done   8 out of   8 | elapsed:  2.6min finished
/home/hamdan1/.conda/envs/scanp/lib/python3.12/site-packages/memento/main.py:181: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
run_eqtl_chr2.sh: line 17: 206870 Killed                  python src/run_eqtl.py -s /project/guomiclab/hamdanz_projects/adsp_r4_rosmap/data/adsp_r4_rosmap/chr2.rosmap.r4.wgs.biallelic.genotypes.mac10.corrected.txt.gz -a data/rnaseq/rosmap_raw_rnaseq_labeled.h5ad -v data/metadata/ROSMAP_covariates.csv -k subject_key --celltype-column major_cell_type -c "$cell" -o "/project/guomiclab/hamdanz_projects/adsp_r4_rosmap/eqtl_results_05222025/chr2_127033851_127233851_gene_range_126633851_127633851/${cell}_chr2_127033851_127233851_rosmap_adsp.csv" --snp-range chr2_127033851_127233851 --gene-range chr2_126633851_127633851
